language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install gcc-multilib; fi
arch:
  - x64
  - x86
matrix:
  allow_failures:
    - arch: x86
  exclude:
    - os: osx
      arch: x86
branches:
  only:
    - master
    - /^release-.*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
